# Generated by Django 4.1 on 2023-08-01 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Academic_Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="N/A", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Chair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="N/A", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("committee_formation_date", models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Committee_Member_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(default="N/A", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Honorific_Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="N/A", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Resource_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(default="N/A", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Thesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thesis_title", models.CharField(default="N/A", max_length=255)),
                ("submission_date", models.DateField(blank=True)),
                ("defense_date", models.DateField(blank=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User_Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="N/A", max_length=255)),
                ("surname", models.CharField(default="N/A", max_length=255)),
                ("date_of_birth", models.DateField(blank=True)),
                ("user_type", models.CharField(default="N/A", max_length=255)),
                ("phone_number", models.CharField(default="N/A", max_length=255)),
                ("email", models.CharField(default="N/A", max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_profile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="thesis.user_profile",
                    ),
                ),
                ("index_number", models.CharField(default="N/A", max_length=255)),
                ("total_espb", models.IntegerField(default=0)),
                ("major", models.CharField(default="N/A", max_length=255)),
                ("gpa", models.FloatField(default=5.0)),
            ],
            bases=("thesis.user_profile",),
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="N/A", max_length=255)),
                (
                    "resource_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thesis.resource_type",
                    ),
                ),
                (
                    "thesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="thesis.thesis"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Committee_Thesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thesis.committee",
                    ),
                ),
                (
                    "thesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="thesis.thesis"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "user_profile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="thesis.user_profile",
                    ),
                ),
                (
                    "academic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thesis.academic_title",
                    ),
                ),
                (
                    "chair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="thesis.chair"
                    ),
                ),
                (
                    "honorific_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thesis.honorific_title",
                    ),
                ),
            ],
            bases=("thesis.user_profile",),
        ),
        migrations.CreateModel(
            name="Committee_Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_number", models.IntegerField()),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thesis.committee",
                    ),
                ),
                (
                    "committee_member_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thesis.committee_member_type",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="thesis.teacher"
                    ),
                ),
            ],
        ),
    ]
