# Generated by Django 4.1 on 2023-08-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thesis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="resource_file",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
