# Generated by Django 4.1 on 2023-08-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thesis", "0002_resource_resource_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="resource_file",
            field=models.FileField(null=True, upload_to="uploads/"),
        ),
    ]
