# Generated by Django 4.1 on 2023-08-03 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("thesis", "0004_rename_original_number_committee_member_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesis",
            name="student",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="thesis.student",
            ),
        ),
    ]
