# Generated by Django 4.1 on 2023-08-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("thesis", "0009_alter_thesis_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thesis",
            name="student",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="theses",
                to="thesis.student",
            ),
        ),
    ]
