# Generated by Django 4.1 on 2023-08-04 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("thesis", "0011_alter_thesis_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesis",
            name="committee",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thesis",
                to="thesis.committee",
            ),
        ),
        migrations.AlterField(
            model_name="committee_member",
            name="committee_member_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="committee_members",
                to="thesis.committee_member_type",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="thesis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="thesis.thesis",
            ),
        ),
        migrations.DeleteModel(
            name="Committee_Thesis",
        ),
    ]
