# Generated by Django 4.1 on 2023-08-04 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("thesis", "0012_thesis_committee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thesis",
            name="committee",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="thesis.committee",
            ),
        ),
    ]
