# Generated by Django 4.1 on 2023-08-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("thesis", "0013_alter_thesis_committee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee_member",
            name="committee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="committee_members",
                to="thesis.committee",
            ),
        ),
        migrations.AlterField(
            model_name="committee_member",
            name="teacher",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="thesis.teacher"
            ),
        ),
        migrations.AlterField(
            model_name="thesis",
            name="committee",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thesis",
                to="thesis.committee",
            ),
        ),
    ]
