# Generated by Django 4.1 on 2023-08-05 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("thesis", "0015_alter_thesis_committee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee_member",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="thesis.teacher"
            ),
        ),
    ]
