# Generated by Django 4.1 on 2023-08-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thesis", "0017_alter_committee_committee_formation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thesis",
            name="submission_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
